sudo: required
services:
  - docker

before_install:
  - docker build -t thevenkatshukla:docker-react -f Dockerfile.dev .

script:
  - docker run thevenkatshukla:docker-react npm run test -- --coverage